spring:
#  servlet:
#    multipart:
#      max-file-size: 20MB #?? ?? ??
#      max-request-size: 30MB
#      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/mold_maker
    username: root
    password: 1111
    
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

server:
  tomcat:
    max-http-form-post-size: 104857600  # 100MB